#!/usr/bin/bash

set -u

LOGO_DIR="/usr/share/home-server-project/fastfetch"
STANDARD_LOGO="${LOGO_DIR}/logo-standard.ansi"
COMPACT_LOGO="${LOGO_DIR}/logo-compact.ansi"

cols="${COLUMNS:-}"
if [[ ! "${cols}" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
    cols="$(tput cols 2>/dev/null || true)"
fi
if [[ ! "${cols}" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
    cols=120
fi

if (( cols < 90 )); then
    cat "${COMPACT_LOGO}"
else
    cat "${STANDARD_LOGO}"
fi
